version: '3.8'
services:
  shop_be:
    container_name: shop_be
    hostname: shop_be
    ports:
      - '8080:8080'
    build:
      dockerfile: Dockerfile
      context: .
      args:
        ENV : local-docker
    networks:
      - shop_be
    volumes:
      - saved-images:/c/Users/Public/Desktop/saved-images
volumes:
  saved-images:
    name: saved-images
    driver: local
networks:
  shop_be:
    driver: bridge
    name: shop_be