management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include:
          - prometheus
          - info
          - metrics
          - health
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
      enabled: true
spring:
  application:
    name: shop_be_production
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: 'true'
    hibernate:
      ddl-auto: update
  flyway:
    user: adi
    password: adi
    url: jdbc:postgresql://db_app:5432/db
    baseline-on-migrate: true
  datasource:
    password: adi
    username: adi
    url: jdbc:postgresql://db_app:5432/db
server:
  port: 8081
global-configurations:
  images:
    path: /c/Users/Adi/Desktop/saved-images/