management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include:
          - prometheus
          - info
          - metrics
          - health
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
      enabled: true
spring:
  application:
    name: shop_be
  jpa:
    properties:
      hibernate:
        use_jdbc_metadata_defaults: true
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
  flyway:
    user: boss
    password: ee1XH4UbawveFSUStfFSOCrInaStMzV0
    url: jdbc:postgresql://dpg-cjc7r545kgrc739o26e0-a.frankfurt-postgres.render.com:5432/db_app_mvra?sslmode=require
    baseline-on-migrate: true
  datasource:
    username: boss
    password: ee1XH4UbawveFSUStfFSOCrInaStMzV0
    url: jdbc:postgresql://dpg-cjc7r545kgrc739o26e0-a.frankfurt-postgres.render.com:5432/db_app_mvra?sslmode=require
server:
  port: 8080
global-configurations:
  images:
    path: C:\Users\Adi\Desktop\saved-images