spring:
  profiles:
    active: prod
#this is used to pass the headers from request that are handle by nginx using https protocol
server:
  forward-headers-strategy: framework
app:
  jwt-secret: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
  jwt-expiration-milliseconds: 604800000