version: '3.8'
services:
  db_app:
    container_name: db_app
    hostname: db_app
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=adi
      - POSTGRES_PASSWORD=adi
      - POSTGRES_DB=db
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - shop_be_admin
      - shop_be_production
volumes:
  db:
    name: db-shop-app-be-volume
    driver: local
networks:
  shop_be_admin:
    external: true
  shop_be_production:
    external: true